name: water
on:
  schedule:
    - cron: '01 10,11,12,13,14,15,16,17,18,20 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: 喝水时间到

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: sender
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: pip install -r ./requirements.txt && python ./water.py

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      WATER_TEMPLATE_ID: ${{ secrets.WATER_TEMPLATE_ID }}
      USER_ID: ${{ secrets.USER_ID }}
